# Generated by Terraform, ansible inventory for ${cluster_name}

[control_plane]
%{ for name, value in control_plane_nodes ~}
${name} ansible_host=${value.ipaddr} ansible_user=debian
%{ endfor }

[workers]
%{ for name, value in worker_nodes ~}
${name} ansible_host=${value.ipaddr} ansible_user=debian
%{ endfor }

# This is for kubectl installation on the local workstation
[workstation]
localhost ansible_connection=local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
cluster_name=${cluster_name}
